spring:

  datasource:
    hikari:
      maximumPoolSize: 20

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

logging:
  level:
    org.springframework: INFO
    danayaspace: DEBUG

server:
  port: 8080

storage:
  location: uploads
  max-file-size: 10485760 # 10MB
  supported-extensions:
      - .jpg
      - .jpeg
      - .png
      - .gif
      - .bmp
      - .webp
      - .heic
      - .heif