spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/danayaspace
    username: danayaspace_user
    password: bVVQAwmMpxWk0wHJkpnAjzVWL8C1fMOU
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  server:
    port: 8080

logging:
  level:
    danayaspace: TRACE

jwt:
  secret: uidghyuhgsdhuh424214dgsdhdsh353gdsh
  expiration: 3000000

storj:
  access-key: jvzskdkwlaa42txaveoevwpw2psq
  secret-key: j2zeskkoogora7eriouyxytcoggc3i375yip2njysjyln7wpyz2qu
  endpoint: https://gateway.storjshare.io
  bucket-name: danayaspace