spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/danaya-space
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  server:
    port: 8080

logging:
  level:
    danayaspace: TRACE

storj:
  access-key: jvzskdkwlaa42txaveoevwpw2psq
  secret-key: j2zeskkoogora7eriouyxytcoggc3i375yip2njysjyln7wpyz2qu
  endpoint: https://gateway.storjshare.io
  bucket-name: danayaspace
  # base-url: https://your-custom-domain.com  # Optional

jwt:
  secret: uidghyuhgsdhuh424214dgsdhdsh353gdsh
  expiration: 30000000
